function cellInfo = object(varargin) 
% OBJECT returns a cell array containing bus object information 
% 
% Optional Input: 'false' will suppress a call to Simulink.Bus.cellToObject 
%                 when the MATLAB file is executed. 
% The order of bus element attributes is as follows:
%   ElementName, Dimensions, DataType, Complexity, SamplingMode, DimensionsMode, Min, Max, DocUnits, Description 

suppressObject = false; 
if nargin == 1 && islogical(varargin{1}) && varargin{1} == false 
    suppressObject = true; 
elseif nargin > 1 
    error('Invalid input argument(s) encountered'); 
end 

cellInfo = { ... 
  { ... 
    'slBus5', ... 
    '', ... 
    '', ... 
    'Auto', ... 
    '-1', ... 
    '0', {... 
{'Airport', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'SID', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Runway', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Waypoint', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Altitude', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Speed_CAS', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Latitude', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Longitude', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
{'Leg_distance', [1 1], 'double', 'real', 'Sample', 'Fixed', [], [], '', ''}; ...
    } ...
  } ...
}'; 

if ~suppressObject 
    % Create bus objects in the MATLAB base workspace 
    Simulink.Bus.cellToObject(cellInfo) 
end 
